### ISSUE TITLE
problem with the forms in OVH server.

### ISSUE THREAD

**Issue by Paul75** [mwillbanks/ZfcTwitterBootstrap#14] opened 2013-01-16 22:40 UTC
Hello,

I have a problems : when I launch first the page who have zfform it not appear normaly. It delete me all the header script link. If I desactivate the module it works. I don't understand why.... In localy I don't reproduce it. But in OVH server it not work. I must reload the page who have the form and then it appear good. Why ?

**Comment by mwillbanks** [comment] 2013-01-16 23:02
Could you provide me a reproducible use case?  I've used this in several environments including production and know others that have as well without having an issue such as this.  Any feedback that would aide in reproduction would be great.

**Comment by Paul75** [comment] 2013-01-16 23:08
I give two page in the sever :
1. http://www.v2.traiter-manipulation.be/site/contact : the page without the form
2. http://www.v2.traiter-manipulation.be/site/services : the page with the form.

I test it in the firefox. I load the contact close firefox and ope the services. In seervice the page appear correctly and in the service not.

Thanks

**Comment by Paul75** [comment] 2013-01-16 23:26
Voilà des images
Bad :
![errorSite](https://f.cloud.github.com/assets/457062/73173/1c493bf0-6034-11e2-9ce8-881d1ad8eca4.png)

Good :
![goodSite](https://f.cloud.github.com/assets/457062/73174/238ec0e2-6034-11e2-835d-b5dc8cd1c381.png)

After reload :
![afterReload](https://f.cloud.github.com/assets/457062/73177/8056ae70-6034-11e2-9a49-da7261b8f9ab.png)

**Comment by mwillbanks** [comment] 2013-01-17 16:18
@Paul75 can you please provide the portion of the view script that is supposed to output the form?  Are you calling echo on the form helper?

**Comment by Paul75** [comment] 2013-01-17 16:29
Hello,

I use Boostrap Twitter.

The view of my page of contact :

``` php
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span9">
            <?php
            if( $this->send == 'true' ) {
                ?>
                <div class="alert alert-success">Votre message a bien été envoyé. On vous répondra dans les meilleures délais.</div>
                <?php
            }
            echo "<h3>Contact</h3>";
            echo "<p>Vous avez des questions à nous poser, besoin de renseignements ?</p><p>N'hésitez pas à nous contacter à l'aide du formulaire ci-dessous. Nous vous répondrons dans les plus brefs délais.</p><br /><br />";

            echo $this->ztbForm($this->form);
            ?>
            <p><b>*</b> Champs requis</p>
        </div>

        <div class="span3">

            <aside class="contact">
                <address class="mbottom">
                    <h5>Christine Calonne</h5>
                    98, rue du 15 août<br/>
                    4430 ANS
                    <br /><br />
                    <b>Tél</b>: 04-223.05.74<br />
                    <b>Portable</b>: 0498-32.26.87
                </address>

                <address class="mbottom">
                    <h5>Cabinet de Liège :</h5>
                    Lundi de 9 heures à 20 heures<br>
                    Mardi de 9 heures à 20 heures<br>
                    Mercredi de 8 heures à 20 heures
                </address>
                <address class="mbottom">
                    <h5>Cabinet de Namur :</h5>
                    17, avenue du Cardinal Mercier<br>
                    Jeudi de 8 heures à 20 heures<br>
                    Vendredi de 10 heures à 20 heures<br>
                    Samedi de 8 h 30 à 19 heures
                </address>
            </aside>
        </div>
    </div>
</div>
```

**Comment by mwillbanks** [comment] 2013-01-17 16:51
Thanks, are there any errors that are coming up?  Is the module added inside of config/application.config.php?

**Comment by Paul75** [comment] 2013-01-17 17:11
You mean if it tell me if see errors in the screen?
I don't  see anything...

Le jeudi 17 janvier 2013, Mike Willbanks notifications@github.com a
écrit :

> Thanks, are there any errors that are coming up? Is the module added
> inside of config/application.config.php?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> <
> https://github.com/notifications/beacon/FK-iqQmBXCXmS650izX6ZAcM-V-HCvGdsfht0FQPo0YWITSP00XcBjT4muMttI7P.gif

## 

Paul

**Comment by mwillbanks** [comment] 2013-01-17 18:22
No; more so in the logs.

**Comment by Paul75** [comment] 2013-01-18 09:00
In my local, and in OVH nothing in the log file....

I don't understand why and where is this problem...

2013/1/17 Mike Willbanks notifications@github.com

> No; more so in the logs.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mwillbanks/ZfcTwitterBootstrap/issues/14#issuecomment-12381350.

## 

Paul

**Comment by Paul75** [comment] 2013-01-19 23:46
Hello,

I test to do the same form without your module, only one input andu using :

```
        $form = $this->form;
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('civilite'));

        echo $this->form()->closeTag();
```

And the page load correctly without must reload it manually first.

I don't know why it is doing when i using the module....

2013/1/18 Paul Borel paul.borel@gmail.com

> In my local, and in OVH nothing in the log file....
> 
> I don't understand why and where is this problem...
> 
> 2013/1/17 Mike Willbanks notifications@github.com
> 
> > No; more so in the logs.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/mwillbanks/ZfcTwitterBootstrap/issues/14#issuecomment-12381350.
> 
> ## 
> 
> Paul

## 

Paul

**Comment by mwillbanks** [comment] 2013-01-20 15:39
What do you have listed for modules in config/application.config.php?  Is the module in there?  To me it seems that the module is not loaded.

**Comment by Paul75** [comment] 2013-01-20 15:44
Hello,

In the file :
<?php
return array(
    'modules' => array(
        'ZfcTwitterBootstrap',
        'ZfcBase',
        'ZfcUser',
        'ZfcAdmin',
        'BjyAuthorize',
        'Application',
        'Admin',
        'Site'
    ),
    'module_listener_options' => array(
        'config_glob_paths'    => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
        'module_paths' => array(
            './module',
            './vendor',
        ),
    ),

);

The module is loaded because it works but I must do F5 to rafrech the page
to see the good page....

2013/1/20 Mike Willbanks notifications@github.com

> What do you have listed for modules in config/application.config.php? Is
> the module in there? To me it seems that the module is not loaded.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mwillbanks/ZfcTwitterBootstrap/issues/14#issuecomment-12472187.

## 

Paul

**Comment by mwillbanks** [comment] 2013-01-21 13:25
Are you doing any full page caching?  I'm sorry it's very hard since I cannot reproduce the behavior on my end.

**Comment by Paul75** [comment] 2013-01-21 14:42
No i'm nothing to do. I take basic skeloton. And basic forms.

I remark that the first load in my head it remove and replace by another
link (ressources//)

Le lundi 21 janvier 2013, Mike Willbanks notifications@github.com a
écrit :

> Are you doing any full page caching? I'm sorry it's very hard since I
> cannot reproduce the behavior on my end.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> <
> https://github.com/notifications/beacon/FK-iqQmBXCXmS650izX6ZAcM-V-HCvGdsfht0FQPo0YWITSP00XcBjT4muMttI7P.gif

## 

Paul

**Comment by babarinde** [comment] 2013-01-21 14:54
Hi,
I think the module works fine
since It has very little to do with the style sheets
Please check your view script or css

**Comment by Paul75** [comment] 2013-01-22 10:43
Hello,

Without the form the pae appear normally.

With the form not.

In my source page I find that :

<head>

<script type="text/javascript">

<style id="smStyle" type="text/css">

<link id="SurfmarkPluginInjectCss" rel="stylesheet" type="text/css"
href="resource://SurfmarkInject/webpage.css">

<script type="text/javascript" src="resource://SurfmarkInject/jQuery.js">

<script type="text/javascript"
src="resource://SurfmarkInject/jQuery.plugins.js">

<script type="text/javascript" src="resource://SurfmarkInject/pdf_custom.js">

<script type="text/javascript" src="resource://SurfmarkInject/spin-min.js">

<script type="text/javascript" src="resource://SurfmarkInject/custom.js">

<script type="text/javascript" src="resource://SurfmarkInject/sm-pdf.js">

</head>

But i havent these script in my code :
- webpage.css
- jQuery.js
- jQuery.plugins.js
- pdf_custom.js
- spin-min.js
- custom.js
- sm-pdf.js

2013/1/21 Odewumi Babarinde notifications@github.com

> Hi,
> I think the module works fine
> since It has very little to do with the style sheets
> Please check your view script or css
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mwillbanks/ZfcTwitterBootstrap/issues/14#issuecomment-12500955.

## 

Paul

**Comment by mwillbanks** [comment] 2013-01-25 20:05
That sounds like you are encountering a fatal error at some point; please enable errors and check the log.  Are you by chance utilizing fieldsets?

**Comment by mwillbanks** [comment] 2013-02-07 18:55
I'm doing to close this one out; cannot reproduce it locally.

**Closed as completed by mwillbanks** 2013-02-07 18:55 UTC
